name: Gatsby Build And Deploy

on: [push]

env:
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Gatsby and Build
        run: |
          echo "install gatsby cli"
          npm install -g gatsby-cli

          echo "cd www"
          cd www

          echo "install required packages"
          npm install

          echo "build"
          gatsby build

          echo "az storage blob upload-batch -s ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/www/public -d \$web --account-name citywidehvac --account-key myaccountkey --overwrite"
          az storage blob upload-batch -s ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/www/public -d \$web --account-name citywidehvac --account-key ${{ secrets.AZURE_STORAGE_KEY }} --overwrite

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/www/public
